### ISSUE TITLE
NFR: Notion of time

### ISSUE THREAD

**Issue by pengnam** [CS2103-AY1819S1-F11-3/main#45]
The task manager must be able to compare between tasks and/or current time to determine which tasks are due earlier and which are due later. 

Suggestion to use unix time stamp

**Comment by unsatisfiedpopcorn** [comment]
How about this, this implements `Comparable` https://docs.oracle.com/javase/8/docs/api/java/util/Date.html

**Comment by remo5000** [comment]
Date works well enough. If we'll be using seconds since epoch, we can consider Instant: https://docs.oracle.com/javase/8/docs/api/java/time/Instant.html

**Comment by pengnam** [comment]
Sure. The storage as unix time stamp is only for persistent storage. (Though I could just standardise a string format and store the date as it is)
